#!/usr/bin/env python 
import os 

def geom_2_com(f_name, coord, symbol, keywords):
    if keywords is None:
        keywords = ['# pm6', '', 'geom', '', '0 1']
    os.makedirs(os.path.dirname(f_name), exist_ok=True)
    with open(f'{f_name}.com', 'w') as f:
        for key in keywords:
            f.write(f"{key}\n")
        for i in range(len(coord)):
            f.write('%s %.6f %.6f %.6f\n' % (symbol[i], coord[i][0], coord[i][1], coord[i][2]))
    f.write('\n')
    return  

def geom_2_dircom(f_name, coord, symbol, keywords):
    if keywords is None:
        keywords = ['# pm6', '', 'geom', '', '0 1']
    os.makedirs(os.path.dirname(f_name), exist_ok=True)
    with open(f'{f_name}', 'w') as f:
        for key in keywords:
            f.write(f"{key}\n")
        for i in range(len(coord)):
            f.write('%s %.6f %.6f %.6f\n' % (symbol[i], coord[i][0], coord[i][1], coord[i][2]))
        f.write('\n')
    return  

def geom_2_xyz(f_name, coord, symbol):
    os.makedirs(os.path.dirname(f_name), exist_ok=True)
    with open(f'{f_name}.xyz', 'w') as f:
        f.write(f"{len(coord)}\n")
        f.write("Generated by 3d_2_input.py\n")
        for i in range(len(coord)):
            f.write('%s %.6f %.6f %.6f\n' % (symbol[i], coord[i][0], coord[i][1], coord[i][2]))
    return 

def read_geom(f_name):
    coord, symbol = [], []
    with open(f_name, 'r') as f:
        lines = f.readlines()
        for line in lines[2:]:
            line = line.strip().split()
            if len(line) == 4:
                symbol.append(line[0])
                coord.append([float(x) for x in line[1:]])
    return coord, symbol

def geom_2_dirin(f_name, coord, symbol, keywords):
    os.makedirs(os.path.dirname(f_name), exist_ok=True)
    with open(f'{f_name}', 'w') as f:
        f.write("$molecule\n")
        f.write("0 1\n")
        for i in range(len(coord)):
            f.write('%s %.6f %.6f %.6f\n' % (symbol[i], coord[i][0], coord[i][1], coord[i][2]))
        for key in keywords:
            f.write(f"{key}\n")
        f.write('\n')
        



